//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuChi
    {
        public int MaCTPhieuChi { get; set; }
        public int MaPhieuChi { get; set; }
        public string NoiDung { get; set; }
        public double SoTienChi { get; set; }
    
        public virtual PhieuChi PhieuChi { get; set; }
    }
}
