//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuThu
    {
        public int MaCTPhieuThu { get; set; }
        public int MaPhieuThu { get; set; }
        public string NoiDung { get; set; }
        public int MaHS { get; set; }
        public double SoTienThu { get; set; }
    
        public virtual PhieuThu PhieuThu { get; set; }
        public virtual HocSinh HocSinh { get; set; }
    }
}
