//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChuyenMon
    {
        public int MaGV { get; set; }
        public string LinhVuc { get; set; }
        public int MaTrinhDo { get; set; }
        public Nullable<System.DateTime> NgayCap { get; set; }
    
        public virtual GiaoVien GiaoVien { get; set; }
        public virtual TrinhDoHocVan TrinhDoHocVan { get; set; }
    }
}
