//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanToc
    {
        public DanToc()
        {
            this.HocSinhs = new HashSet<HocSinh>();
        }
    
        public int MaDT { get; set; }
        public string TenDT { get; set; }
    
        public virtual ICollection<HocSinh> HocSinhs { get; set; }
    }
}
