//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoVien
    {
        public GiaoVien()
        {
            this.ChuNhiemLops = new HashSet<ChuNhiemLop>();
            this.ChuyenMons = new HashSet<ChuyenMon>();
            this.PhanCongGiangDays = new HashSet<PhanCongGiangDay>();
        }
    
        public int MaGV { get; set; }
        public string TenGV { get; set; }
        public string DiaChi { get; set; }
        public Nullable<bool> GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiThieu { get; set; }
    
        public virtual ICollection<ChuNhiemLop> ChuNhiemLops { get; set; }
        public virtual ICollection<ChuyenMon> ChuyenMons { get; set; }
        public virtual ICollection<PhanCongGiangDay> PhanCongGiangDays { get; set; }
    }
}
