//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiTinhTrangHoSo
    {
        public LoaiTinhTrangHoSo()
        {
            this.TinhTrangHoSoes = new HashSet<TinhTrangHoSo>();
        }
    
        public int MaLoaiTinhTrangHoSo { get; set; }
        public string TenLoaiTinhTrangHoSo { get; set; }
    
        public virtual ICollection<TinhTrangHoSo> TinhTrangHoSoes { get; set; }
    }
}
