//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiPhieuDiemDanh
    {
        public LoaiPhieuDiemDanh()
        {
            this.PhieuDiemDanhs = new HashSet<PhieuDiemDanh>();
        }
    
        public int MaLoaiPhieuDiemDanh { get; set; }
        public string TenLoaiPhieuDiemDanh { get; set; }
    
        public virtual ICollection<PhieuDiemDanh> PhieuDiemDanhs { get; set; }
    }
}
