//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiPhieuThu
    {
        public LoaiPhieuThu()
        {
            this.PhieuThus = new HashSet<PhieuThu>();
        }
    
        public int MaLoaiPhieuThu { get; set; }
        public string TenLoaiPhieuThu { get; set; }
    
        public virtual ICollection<PhieuThu> PhieuThus { get; set; }
    }
}
