//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lop
    {
        public Lop()
        {
            this.ChuNhiemLops = new HashSet<ChuNhiemLop>();
            this.LopHocs = new HashSet<LopHoc>();
            this.PhanCongGiangDays = new HashSet<PhanCongGiangDay>();
            this.PhieuChis = new HashSet<PhieuChi>();
            this.PhieuThus = new HashSet<PhieuThu>();
        }
    
        public int MaLop { get; set; }
        public string TenLop { get; set; }
        public int MaKhoi { get; set; }
    
        public virtual ICollection<ChuNhiemLop> ChuNhiemLops { get; set; }
        public virtual Khoi Khoi { get; set; }
        public virtual ICollection<LopHoc> LopHocs { get; set; }
        public virtual ICollection<PhanCongGiangDay> PhanCongGiangDays { get; set; }
        public virtual ICollection<PhieuChi> PhieuChis { get; set; }
        public virtual ICollection<PhieuThu> PhieuThus { get; set; }
    }
}
