//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class csdl_nhapmoncnpmEntities : DbContext
    {
        public csdl_nhapmoncnpmEntities()
            : base("name=csdl_nhapmoncnpmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<BanHoc> BanHocs { get; set; }
        public DbSet<ChiTietPhieuChi> ChiTietPhieuChis { get; set; }
        public DbSet<ChiTietPhieuThu> ChiTietPhieuThus { get; set; }
        public DbSet<ChuNhiemLop> ChuNhiemLops { get; set; }
        public DbSet<DanToc> DanTocs { get; set; }
        public DbSet<Diem> Diems { get; set; }
        public DbSet<DiemTongKet> DiemTongKets { get; set; }
        public DbSet<GiaoVien> GiaoViens { get; set; }
        public DbSet<HanhKiem> HanhKiems { get; set; }
        public DbSet<HocSinh> HocSinhs { get; set; }
        public DbSet<KhenThuong> KhenThuongs { get; set; }
        public DbSet<Khoi> Khois { get; set; }
        public DbSet<KyLuat> KyLuats { get; set; }
        public DbSet<LoaiHanhKiem> LoaiHanhKiems { get; set; }
        public DbSet<LoaiPhieuDiemDanh> LoaiPhieuDiemDanhs { get; set; }
        public DbSet<LoaiPhieuThu> LoaiPhieuThus { get; set; }
        public DbSet<LoaiTinhTrangHoSo> LoaiTinhTrangHoSoes { get; set; }
        public DbSet<Lop> Lops { get; set; }
        public DbSet<LopHoc> LopHocs { get; set; }
        public DbSet<MonHoc> MonHocs { get; set; }
        public DbSet<NguoiThan> NguoiThans { get; set; }
        public DbSet<PhanCongGiangDay> PhanCongGiangDays { get; set; }
        public DbSet<PhieuChi> PhieuChis { get; set; }
        public DbSet<PhieuDiemDanh> PhieuDiemDanhs { get; set; }
        public DbSet<PhieuThu> PhieuThus { get; set; }
        public DbSet<TrinhDoHocVan> TrinhDoHocVans { get; set; }
        public DbSet<XepLoai> XepLoais { get; set; }
        public DbSet<BangDiem> BangDiems { get; set; }
        public DbSet<ChuyenMon> ChuyenMons { get; set; }
        public DbSet<TinhTrangHoSo> TinhTrangHoSoes { get; set; }
    }
}
