//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonHoc
    {
        public MonHoc()
        {
            this.BangDiems = new HashSet<BangDiem>();
            this.PhanCongGiangDays = new HashSet<PhanCongGiangDay>();
        }
    
        public int MaMon { get; set; }
        public string TenMon { get; set; }
        public int HeSo { get; set; }
        public int MaBan { get; set; }
    
        public virtual BanHoc BanHoc { get; set; }
        public virtual ICollection<BangDiem> BangDiems { get; set; }
        public virtual ICollection<PhanCongGiangDay> PhanCongGiangDays { get; set; }
    }
}
