//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguoiThan
    {
        public string SDT { get; set; }
        public string HoTen { get; set; }
        public string QuanHe { get; set; }
        public string DiaChi { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public int MaHS { get; set; }
    
        public virtual HocSinh HocSinh { get; set; }
    }
}
