//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuDiemDanh
    {
        public int MaHS { get; set; }
        public System.DateTime ThoiGian { get; set; }
        public int MaLoaiPhieuDiemDanh { get; set; }
        public int HocKy { get; set; }
    
        public virtual HocSinh HocSinh { get; set; }
        public virtual LoaiPhieuDiemDanh LoaiPhieuDiemDanh { get; set; }
    }
}
