//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuThu
    {
        public PhieuThu()
        {
            this.ChiTietPhieuThus = new HashSet<ChiTietPhieuThu>();
        }
    
        public int MaPhieuThu { get; set; }
        public int MaLop { get; set; }
        public string NoiDung { get; set; }
        public int MaLoaiPhieuThu { get; set; }
        public int HocKy { get; set; }
        public int NamHoc { get; set; }
        public Nullable<System.DateTime> NgayTaoPhieu { get; set; }
        public double SoTienThu { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
    
        public virtual ICollection<ChiTietPhieuThu> ChiTietPhieuThus { get; set; }
        public virtual LoaiPhieuThu LoaiPhieuThu { get; set; }
        public virtual Lop Lop { get; set; }
    }
}
