//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrinhDoHocVan
    {
        public TrinhDoHocVan()
        {
            this.ChuyenMons = new HashSet<ChuyenMon>();
        }
    
        public int MaTrinhDo { get; set; }
        public string TenTrinhDo { get; set; }
    
        public virtual ICollection<ChuyenMon> ChuyenMons { get; set; }
    }
}
