//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace View
{
    using System;
    using System.Collections.Generic;
    
    public partial class XepLoai
    {
        public XepLoai()
        {
            this.DiemTongKets = new HashSet<DiemTongKet>();
        }
    
        public int MaXepLoai { get; set; }
        public string TenXepLoai { get; set; }
    
        public virtual ICollection<DiemTongKet> DiemTongKets { get; set; }
    }
}
